[hour_factor]
peak = 1.2
offpeak = 0.7

[water_temp_factor]
cold = 0.7
medium = 0.9
warm = 1.1

[air_temp_factor]
cold = 0.6
medium = 0.8
hot = 1.2

[weather_condition_factor]
Clear = 1.3
Cloudy = 1.0
Rain = 0.7
Thunderstorm = 0.5
Unknown = 1.0
